import type {OxlintConfig} from 'oxlint';

export interface BaseConfigOptions {
    strict?: boolean;
}

export function createBaseConfig(options: BaseConfigOptions = {}): OxlintConfig {
    const {strict = false} = options;

    return {
        plugins: ['eslint'],
        rules: {
            'accessor-pairs': 'off',
            'array-callback-return': ['error', {checkForEach: true, allowVoid: true}],
            'arrow-body-style': 'off',
            'block-scoped-var': strict ? 'warn' : 'off',
            'capitalized-comments': 'off',
            'class-methods-use-this': 'off',
            complexity: strict ? ['warn', 10] : 'off',
            'constructor-super': 'error',
            curly: ['error', 'all'],
            'default-case': 'off',
            'default-case-last': 'error',
            'default-param-last': 'off',
            eqeqeq: ['error', 'always', {null: 'ignore'}],
            'for-direction': 'off',
            'func-names': strict ? ['warn', 'always'] : 'off',
            'func-style': 'off',
            'getter-return': 'warn',
            'grouped-accessor-pairs': 'off',
            'guard-for-in': 'warn',
            'id-length': 'off',
            'init-declarations': strict ? 'warn' : 'off',
            'max-classes-per-file': 'off',
            'max-depth': ['warn', strict ? 3 : 6],
            'max-lines': strict ? ['warn', 800] : 'off',
            'max-lines-per-function': 'off',
            'max-nested-callbacks': ['warn', 3],
            'max-params': ['warn', 6],
            'max-statements': strict ? ['warn', 30, {ignoreTopLevelFunctions: true}] : 'off',
            'new-cap': 'error',
            'no-alert': strict ? 'warn' : 'off',
            'no-array-constructor': 'error',
            'no-async-promise-executor': 'warn',
            'no-await-in-loop': 'off',
            'no-bitwise': 'off',
            'no-caller': 'off',
            'no-case-declarations': 'off',
            'no-class-assign': 'warn',
            'no-compare-neg-zero': 'off',
            'no-cond-assign': 'off',
            'no-console': 'off',
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'warn',
            'no-constant-condition': 'warn',
            'no-constructor-return': 'error',
            'no-continue': 'off',
            'no-control-regex': 'off',
            'no-debugger': 'error',
            'no-delete-var': 'warn',
            'no-div-regex': 'off',
            'no-dupe-class-members': 'warn',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'warn',
            'no-duplicate-case': 'error',
            'no-duplicate-imports': 'off',
            'no-else-return': 'warn',
            'no-empty': 'off',
            'no-empty-character-class': 'error',
            'no-empty-function': 'off',
            'no-empty-pattern': 'error',
            'no-empty-static-block': 'off',
            'no-eq-null': 'off',
            'no-eval': 'warn',
            'no-ex-assign': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'warn',
            'no-extra-boolean-cast': 'warn',
            'no-extra-label': 'off',
            'no-fallthrough': strict ? 'error' : 'warn',
            'no-func-assign': 'warn',
            'no-global-assign': strict ? 'error' : 'off',
            'no-implicit-coercion': 'off',
            'no-import-assign': 'error',
            'no-inline-comments': 'off',
            'no-inner-declarations': strict ? 'error' : 'warn',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'warn',
            'no-iterator': 'error',
            'no-label-var': 'warn',
            'no-labels': ['warn', {allowLoop: true}],
            'no-lone-blocks': 'warn',
            'no-lonely-if': strict ? 'error' : 'off',
            'no-loop-func': 'warn',
            'no-loss-of-precision': 'off',
            'no-magic-numbers': 'off',
            'no-misleading-character-class': 'error',
            'no-multi-assign': 'off',
            'no-multi-str': 'warn',
            'no-negated-condition': strict ? 'warn' : 'off',
            'no-nested-ternary': 'off',
            'no-new': strict ? 'error' : 'off',
            'no-new-func': strict ? 'error' : 'off',
            'no-new-native-nonconstructor': 'error',
            'no-new-wrappers': 'error',
            'no-nonoctal-decimal-escape': 'off',
            'no-obj-calls': 'error',
            'no-object-constructor': 'off',
            'no-param-reassign': 'off',
            'no-plusplus': 'off',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-prototype-builtins': 'off',
            'no-redeclare': strict ? 'error' : 'warn',
            'no-regex-spaces': strict ? 'error' : 'off',
            'no-restricted-globals': 'off',
            'no-restricted-imports': 'off',
            'no-return-assign': [strict ? 'error' : 'warn', 'except-parens'],
            'no-script-url': 'warn',
            'no-self-assign': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'off',
            'no-setter-return': 'error',
            'no-shadow': 'off',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': strict ? 'error' : 'warn',
            'no-template-curly-in-string': 'off',
            'no-ternary': 'off',
            'no-this-before-super': 'error',
            'no-throw-literal': 'error',
            'no-unassigned-vars': 'error',
            'no-undef': 'error',
            'no-undefined': 'off',
            'no-unexpected-multiline': 'error',
            'no-unmodified-loop-condition': 'warn',
            'no-unneeded-ternary': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-expressions': ['warn', {allowShortCircuit: true}],
            'no-unused-labels': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': ['warn', {vars: 'local', args: 'none'}],
            'no-use-before-define': ['error', {variables: false, classes: false, functions: true}],
            'no-useless-backreference': 'warn',
            'no-useless-call': 'warn',
            'no-useless-catch': 'warn',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'warn',
            'no-useless-constructor': strict ? 'error' : 'warn',
            'no-useless-escape': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'off',
            'no-var': 'warn',
            'no-void': 'off',
            'no-warning-comments': 'off',
            'no-with': strict ? 'error' : 'warn',
            'operator-assignment': 'off',
            'prefer-const': 'off',
            'prefer-destructuring': 'off',
            'prefer-exponentiation-operator': 'off',
            'prefer-numeric-literals': strict ? 'error' : 'off',
            'prefer-object-has-own': 'off',
            'prefer-object-spread': 'off',
            'prefer-promise-reject-errors': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': strict ? 'warn' : 'off',
            'prefer-template': 'off',
            'preserve-caught-error': 'off',
            radix: 'error',
            'require-await': 'off',
            'require-yield': 'off',
            'sort-imports': 'off',
            'sort-keys': 'off',
            'sort-vars': 'off',
            'symbol-description': 'warn',
            'unicode-bom': 'warn',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'vars-on-top': 'off',
            yoda: 'warn',
        },
    };
}
