import type {OxlintConfig} from 'oxlint';

export interface TypeScriptConfigOptions {
    strict?: boolean;
}

export function createTypeScriptConfig(options: TypeScriptConfigOptions = {}): OxlintConfig {
    const {strict = false} = options;

    return {
        plugins: ['typescript'],
        rules: {
            'constructor-super': 'off',
            'getter-return': 'off',
            'init-declarations': 'error',
            'no-class-assign': 'off',
            'no-const-assign': 'off',
            'no-dupe-class-members': 'off',
            'no-dupe-keys': 'off',
            'no-duplicate-imports': 'off',
            'no-func-assign': 'off',
            'no-import-assign': 'off',
            'no-obj-calls': 'off',
            'no-redeclare': 'off',
            'no-setter-return': 'off',
            'no-this-before-super': 'off',
            'no-undef': 'off',
            'no-unreachable': 'off',
            'no-unsafe-negation': 'off',
            'no-with': 'off',
            'typescript/adjacent-overload-signatures': 'error',
            'typescript/array-type': ['error', {default: 'array-simple', readonly: 'array-simple'}],
            'typescript/await-thenable': 'warn',
            'typescript/ban-ts-comment': strict ? 'warn' : 'off',
            'typescript/ban-tslint-comment': 'off',
            'typescript/ban-types': 'off',
            'typescript/class-literal-property-style': 'off',
            'typescript/consistent-generic-constructors': ['error', 'constructor'],
            'typescript/consistent-indexed-object-style': 'off',
            'typescript/consistent-return': 'off',
            'typescript/consistent-type-assertions': 'error',
            'typescript/consistent-type-definitions': ['error', 'interface'],
            'typescript/consistent-type-exports': strict ? 'error' : 'off',
            'typescript/consistent-type-imports': strict ? 'error' : 'off',
            'typescript/dot-notation': ['error', {allowIndexSignaturePropertyAccess: true}],
            'typescript/explicit-function-return-type': 'off',
            'typescript/explicit-module-boundary-types': 'off',
            'typescript/no-array-delete': 'error',
            'typescript/no-base-to-string': 'off',
            'typescript/no-confusing-non-null-assertion': 'off',
            'typescript/no-confusing-void-expression': 'off',
            'typescript/no-deprecated': 'off',
            'typescript/no-duplicate-enum-values': 'off',
            'typescript/no-duplicate-type-constituents': strict ? 'warn' : 'off',
            'typescript/no-dynamic-delete': 'off',
            'typescript/no-empty-interface': 'warn',
            'typescript/no-empty-object-type': 'warn',
            'typescript/no-explicit-any': 'off',
            'typescript/no-extra-non-null-assertion': 'error',
            'typescript/no-extraneous-class': 'error',
            'typescript/no-floating-promises': strict ? ['error', {ignoreVoid: true}] : 'off',
            'typescript/no-for-in-array': 'error',
            'typescript/no-implied-eval': 'warn',
            'typescript/no-import-type-side-effects': 'error',
            'typescript/no-inferrable-types': 'off',
            'typescript/no-invalid-void-type': 'off',
            'typescript/no-meaningless-void-operator': 'off',
            'typescript/no-misused-new': 'error',
            'typescript/no-misused-promises': 'off',
            'typescript/no-misused-spread': 'error',
            'typescript/no-mixed-enums': 'error',
            'typescript/no-namespace': 'error',
            'typescript/no-non-null-asserted-nullish-coalescing': 'error',
            'typescript/no-non-null-asserted-optional-chain': 'warn',
            'typescript/no-non-null-assertion': 'error',
            'typescript/no-redundant-type-constituents': 'warn',
            'typescript/no-require-imports': 'error',
            'typescript/no-restricted-types': 'off',
            'typescript/no-this-alias': 'error',
            'typescript/no-unnecessary-boolean-literal-compare': 'error',
            'typescript/no-unnecessary-condition': 'warn',
            'typescript/no-unnecessary-parameter-property-assignment': 'off',
            'typescript/no-unnecessary-qualifier': 'error',
            'typescript/no-unnecessary-template-expression': 'error',
            'typescript/no-unnecessary-type-arguments': 'warn',
            'typescript/no-unnecessary-type-assertion': 'error',
            'typescript/no-unnecessary-type-constraint': 'error',
            'typescript/no-unnecessary-type-conversion': 'off',
            'typescript/no-unnecessary-type-parameters': 'off',
            'typescript/no-unsafe-argument': 'error',
            'typescript/no-unsafe-assignment': 'error',
            'typescript/no-unsafe-call': 'error',
            'typescript/no-unsafe-declaration-merging': strict ? 'error' : 'off',
            'typescript/no-unsafe-enum-comparison': 'error',
            'typescript/no-unsafe-function-type': 'off',
            'typescript/no-unsafe-member-access': 'off',
            'typescript/no-unsafe-return': strict ? 'error' : 'off',
            'typescript/no-unsafe-type-assertion': 'off',
            'typescript/no-unsafe-unary-minus': 'error',
            'typescript/no-useless-default-assignment': 'off',
            'typescript/no-useless-empty-export': 'off',
            'typescript/no-var-requires': 'error',
            'typescript/no-wrapper-object-types': 'off',
            'typescript/non-nullable-type-assertion-style': 'error',
            'typescript/only-throw-error': 'error',
            'typescript/parameter-properties': 'off',
            'typescript/prefer-as-const': 'error',
            'typescript/prefer-enum-initializers': 'error',
            'typescript/prefer-find': 'warn',
            'typescript/prefer-for-of': 'error',
            'typescript/prefer-function-type': 'error',
            'typescript/prefer-includes': 'warn',
            'typescript/prefer-literal-enum-member': 'off',
            'typescript/prefer-namespace-keyword': 'error',
            'typescript/prefer-nullish-coalescing': 'warn',
            'typescript/prefer-optional-chain': 'warn',
            'typescript/prefer-promise-reject-errors': 'error',
            'typescript/prefer-readonly': 'error',
            'typescript/prefer-readonly-parameter-types': 'off',
            'typescript/prefer-reduce-type-parameter': 'off',
            'typescript/prefer-regexp-exec': 'warn',
            'typescript/prefer-return-this-type': 'warn',
            'typescript/prefer-string-starts-ends-with': 'warn',
            'typescript/prefer-ts-expect-error': 'error',
            'typescript/promise-function-async': 'off',
            'typescript/related-getter-setter-pairs': 'off',
            'typescript/require-array-sort-compare': 'off',
            'typescript/require-await': 'off',
            'typescript/restrict-plus-operands': 'error',
            'typescript/restrict-template-expressions': 'off',
            'typescript/return-await': 'off',
            'typescript/strict-boolean-expressions': 'off',
            'typescript/strict-void-return': 'off',
            'typescript/switch-exhaustiveness-check': 'error',
            'typescript/triple-slash-reference': 'error',
            'typescript/unbound-method': 'off',
            'typescript/unified-signatures': 'warn',
            'typescript/use-unknown-in-catch-callback-variable': 'error',
        },
    };
}
